export type AppLanguage = 'es' | 'en' | 'fr';
export type LanguagePreference = 'system' | AppLanguage;

export const LANGUAGE_OPTIONS: { value: LanguagePreference; label: string }[] = [
  { value: 'system', label: 'System' },
  { value: 'es', label: 'Español' },
  { value: 'en', label: 'English' },
  { value: 'fr', label: 'Français' },
];

export const LANGUAGE_LOCALES: Record<AppLanguage, string> = {
  es: 'es-ES',
  en: 'en-US',
  fr: 'fr-FR',
};

export function resolveLanguage(languageCode?: string | null): AppLanguage {
  const baseLanguage = languageCode?.toLocaleLowerCase().split(/[-_]/)[0];
  if (baseLanguage === 'es' || baseLanguage === 'fr') return baseLanguage;
  return 'en';
}

const messages = {
  es: {
    summary: 'Resumen', transactions: 'Movimientos', add: 'Añadir', planning: 'Planificación', categories: 'Categorías',
    day: 'Día', week: 'Semana', month: 'Mes', year: 'Año', custom: 'Personalizado', totalPeriod: 'Total del periodo', addExpense: 'Añadir gasto',
    settings: 'Ajustes', settingsSubtitle: 'Tu cuenta y preferencias de ExpenseTracker.', account: 'Cuenta', signedIn: 'Sesión iniciada',
    currencies: 'Divisas', inputCurrency: 'Moneda de entrada', displayedCurrency: 'Moneda mostrada', exchangeRate: 'Tipo de cambio', appearance: 'Apariencia', light: 'Claro', dark: 'Oscuro',
    language: 'Idioma', languageSubtitle: 'Idioma de la aplicación', systemLanguage: 'Sistema',
    plannedMovements: 'Movimientos previstos', automatic: 'Automático', manual: 'Manual', automaticDescription: 'Se marcan como realizados al abrir la aplicación en la fecha prevista.', manualDescription: 'Permanecen pendientes hasta que los confirmes.',
    categorization: 'Categorización', information: 'Información', signOut: 'Cerrar sesión', signingOut: 'Cerrando sesión…', back: 'Volver',
    chooseCategory: 'Elegir categoría', searchCategory: 'Buscar categoría...', searchOrChoose: 'Busca o selecciona una categoría.', noCategories: 'No encontramos ninguna categoría.', allCategories: 'Todas las categorías', noCategoryFilter: 'No limitar los resultados por categoría.',
    concept: 'Concepto', amount: 'Importe', date: 'Fecha', category: 'Categoría', today: 'Hoy', yesterday: 'Ayer', anotherDay: 'Otro día', plannedExpense: 'Gasto previsto', saveExpense: 'Guardar gasto',
    expense: 'Gasto', income: 'Ingreso', newExpense: 'Nuevo gasto', addFewSteps: 'Añádelo en unos pocos pasos.', conceptPlaceholder: 'Café, compra…', plannedPending: 'Se guardará como pendiente hasta esa fecha.', searching: 'Buscando…', selected: 'Seleccionada', change: 'Cambiar', suggested: 'Sugeridas', viewAllCategories: 'Ver todas las categorías', savePlannedExpense: 'Guardar gasto previsto', expenseCurrency: 'Divisa del gasto', invalidAmount: 'Introduce un importe válido.', selectCategory: 'Selecciona una categoría.', expenseSaved: 'Gasto añadido', plannedExpenseSaved: 'Gasto previsto guardado', expenseSaveError: 'No se pudo guardar el gasto.',
    markCompleted: 'Marcar como realizado', movementCompleted: 'Movimiento realizado', movementCompleteError: 'No se pudo completar el movimiento.',
    newIncome: 'Nuevo ingreso', incomeSubtitle: 'Registra nómina, devolución u otra entrada.', incomePlaceholder: 'Nómina, devolución…', incomeInfo: 'Este ingreso contará para el balance y el ahorro del mes.', saveIncome: 'Guardar ingreso', incomeCurrency: 'Divisa del ingreso', incomeSaved: 'Ingreso añadido', incomeSaveError: 'No se pudo guardar el ingreso.',
    expenses: 'Gastos', incomes: 'Ingresos', transactionsSubtitle: 'Consulta y edita tus gastos e ingresos.', all: 'Todos', thisWeek: 'Esta semana', thisMonth: 'Este mes', searchMovements: 'Descripción, categoría o importe', hideUpcomingExpenses: 'Ocultar próximos gastos', viewUpcomingExpenses: 'Ver próximos gastos', upcomingVisible: 'La sección Próximos está visible', plannedAndRecurring: 'Pagos previstos y recurrentes', filters: 'Filtros', noExpenses: 'Aún no hay gastos', noResults: 'No hay resultados', noExpensesHint: 'Los gastos que añadas aparecerán aquí.', noResultsHint: 'Prueba con otra búsqueda o quita algún filtro.', clearSearchFilters: 'Limpiar búsqueda y filtros', upcoming: 'Próximos', planned: 'Previsto', recurring: 'Recurrente', uncategorized: 'Sin categoría', total: 'en total',
    planningSubtitle: 'Tu balance, límites y próximos movimientos.', monthBalance: 'Balance del mes', totalExpenses: 'Gastos totales', savings: 'Ahorro', upcomingMovements: 'Próximos movimientos', upcoming12Months: 'Todos los previstos · recurrentes a 12 meses', viewAll: 'Ver todos', noUpcoming: 'No tienes ingresos ni gastos próximos.', budgets: 'Presupuestos', monthLimits: 'Límites para este mes', addAction: 'Añadir', createBudgetHint: 'Crea un límite total o por categoría.', totalBudget: 'Presupuesto total', used: 'utilizado', recurringPlural: 'Recurrentes', recurringForecast: 'Cada repetición aparece en la previsión', recurringEmpty: 'Añade alquiler, nómina o suscripciones.', recentEntries: 'Entradas recientes', addIncomeHint: 'Añade un ingreso para calcular tu ahorro.', weekly: 'Semanal', monthly: 'Mensual', yearly: 'Anual', next: 'próximo', tapToEdit: 'toca para editar',
    categoriesSubtitle: 'Personaliza cómo organizas tu dinero.', editCategory: 'Editar categoría', newCategory: 'Nueva categoría', name: 'Nombre', description: 'Descripción', icon: 'Icono', color: 'Color', saveChanges: 'Guardar cambios', saving: 'Guardando…', deleteCategory: 'Eliminar categoría',
    authSubtitle: 'Entiende tu dinero sin perder tiempo registrándolo.', email: 'Email', password: 'Contraseña', signIn: 'Iniciar sesión', or: 'o', createAccount: 'Crear una cuenta', incompleteData: 'Datos incompletos', enterCredentials: 'Introduce tu email y contraseña.', shortPassword: 'Contraseña demasiado corta', sixCharacters: 'Utiliza al menos 6 caracteres.', checkEmail: 'Revisa tu correo', confirmEmail: 'Te hemos enviado un email para confirmar tu cuenta.',
    editExpense: 'Editar gasto', editIncome: 'Editar ingreso', editSubtitle: 'Actualiza los datos que necesites.', optionalDescription: 'Descripción opcional', chooseCategoryAction: 'Seleccionar categoría', changeCategory: 'Cambiar categoría', deleteExpense: 'Eliminar gasto', deleteIncome: 'Eliminar ingreso', deleteConfirm: 'Esta acción no se puede deshacer.', delete: 'Eliminar', updatedExpense: 'Gasto actualizado', updatedIncome: 'Ingreso actualizado',
    chooseCurrency: 'Elegir divisa', commonCurrency: 'Elige una divisa habitual.', spent: 'gastado',
    close: 'Cerrar', filterExpenses: 'Filtrar gastos', combineCriteria: 'Combina los criterios que necesites.', status: 'Estado', completed: 'Realizados', origin: 'Origen', manualSource: 'Manual', textSource: 'Texto', voiceSource: 'Voz', minAmount: 'Mínimo', maxAmount: 'Máximo', sortBy: 'Ordenar por', newest: 'Más reciente', oldest: 'Más antiguo', highest: 'Mayor importe', lowest: 'Menor importe', clearFilters: 'Limpiar filtros', applyFilters: 'Aplicar filtros', tapToChange: 'Toca para cambiar', noLimit: 'Sin límite', viewResults: 'Ver resultados', filterByCategory: 'Filtrar por categoría',
    setupMissing: 'Falta completar la configuración', setupPlanning: 'Prepara Planificación para activar ingresos, presupuestos y recurrencias.', newBudget: 'Nuevo presupuesto', editBudget: 'Editar presupuesto', scope: 'Ámbito', limit: 'Límite', budgetMonth: 'Mes del presupuesto', allMonthlySpend: 'Todo el gasto mensual', saveBudget: 'Guardar presupuesto', budgetEditorHint: 'Límite mensual para', invalidLimit: 'Introduce un límite válido.', budgetSaved: 'Presupuesto guardado', budgetUpdated: 'Presupuesto actualizado', budgetSaveError: 'No se pudo guardar el presupuesto. Comprueba que no exista otro para el mismo ámbito y mes.', deleteBudget: 'Eliminar presupuesto', budgetDeleteConfirm: '¿Quieres eliminar este límite mensual?', budgetDeleted: 'Presupuesto eliminado', budgetDeleteError: 'No se pudo eliminar el presupuesto.', editRecurring: 'Editar recurrente', newRecurring: 'Nuevo recurrente', frequency: 'Frecuencia', nextDue: 'Próximo vencimiento', createRecurring: 'Crear recurrencia', deleteRecurring: 'Eliminar recurrencia', recurringPlaceholder: 'Alquiler, nómina, plataforma…',
    privacy: 'Privacidad', privacyDescription: 'Los conceptos se procesan en tu dispositivo.', connection: 'Conexión', connected: 'Servicio conectado', offlineRetry: 'Sin conexión · toca para reintentar', checkingConnection: 'Comprobando conexión…', version: 'Versión', offline: 'Sin conexión', checkInternet: 'Comprueba Internet y toca para reintentar.',
    intelligentEngine: 'Motor inteligente', engineReady: 'Cargado y listo para clasificar', engineFallback: 'No disponible · se usa la clasificación básica', engineInstalled: 'Disponible en la aplicación instalada', engineDownloading: 'Descargando en el dispositivo', engineStarting: 'Descarga completa · iniciando…', engineChecking: 'Comprobando el motor local…',
    expenseDeleted: 'Gasto eliminado', incomeDeleted: 'Ingreso eliminado',
    categorizationStartError: 'La categorización inteligente no pudo iniciarse', basicCategorizationActive: 'La categorización básica sigue activa. Toca para reintentar.', downloadingLocal: 'Descargando recursos locales', preparingLocal: 'Preparando categorización', keepUsingApp: 'Puedes seguir usando la aplicación.', latestRate: 'Obteniendo la cotización más reciente…', cachedRate: 'Sin conexión · se mantiene el último cambio disponible', rateReference: 'Referencia diaria de Frankfurter · toca para actualizar',
    signOutError: 'No se pudo cerrar la sesión.', rateUpdated: 'Tipo de cambio actualizado', rateUpdateError: 'No se pudo actualizar el cambio', recurrenceSkipped: 'Movimiento omitido. La siguiente repetición sigue programada.',
    customPeriod: 'Periodo personalizado', from: 'Desde', to: 'Hasta', apply: 'Aplicar', cancel: 'Cancelar',
  },
  en: {
    summary: 'Summary', transactions: 'Transactions', add: 'Add', planning: 'Planning', categories: 'Categories',
    day: 'Day', week: 'Week', month: 'Month', year: 'Year', custom: 'Custom', totalPeriod: 'Period total', addExpense: 'Add expense',
    settings: 'Settings', settingsSubtitle: 'Your ExpenseTracker account and preferences.', account: 'Account', signedIn: 'Signed in',
    currencies: 'Currencies', inputCurrency: 'Entry currency', displayedCurrency: 'Display currency', exchangeRate: 'Exchange rate', appearance: 'Appearance', light: 'Light', dark: 'Dark',
    language: 'Language', languageSubtitle: 'Application language', systemLanguage: 'System',
    plannedMovements: 'Planned transactions', automatic: 'Automatic', manual: 'Manual', automaticDescription: 'They are marked as completed when you open the app on their due date.', manualDescription: 'They remain pending until you confirm them.',
    categorization: 'Categorization', information: 'Information', signOut: 'Sign out', signingOut: 'Signing out…', back: 'Back',
    chooseCategory: 'Choose category', searchCategory: 'Search category...', searchOrChoose: 'Search or choose a category.', noCategories: 'No categories found.', allCategories: 'All categories', noCategoryFilter: 'Do not filter results by category.',
    concept: 'Concept', amount: 'Amount', date: 'Date', category: 'Category', today: 'Today', yesterday: 'Yesterday', anotherDay: 'Another day', plannedExpense: 'Planned expense', saveExpense: 'Save expense',
    expense: 'Expense', income: 'Income', newExpense: 'New expense', addFewSteps: 'Add it in just a few steps.', conceptPlaceholder: 'Coffee, groceries…', plannedPending: 'It will remain pending until that date.', searching: 'Searching…', selected: 'Selected', change: 'Change', suggested: 'Suggested', viewAllCategories: 'View all categories', savePlannedExpense: 'Save planned expense', expenseCurrency: 'Expense currency', invalidAmount: 'Enter a valid amount.', selectCategory: 'Choose a category.', expenseSaved: 'Expense added', plannedExpenseSaved: 'Planned expense saved', expenseSaveError: 'The expense could not be saved.',
    markCompleted: 'Mark as completed', movementCompleted: 'Transaction completed', movementCompleteError: 'The transaction could not be completed.',
    newIncome: 'New income', incomeSubtitle: 'Record salary, refunds, or other income.', incomePlaceholder: 'Salary, refund…', incomeInfo: 'This income will count towards your monthly balance and savings.', saveIncome: 'Save income', incomeCurrency: 'Income currency', incomeSaved: 'Income added', incomeSaveError: 'The income could not be saved.',
    expenses: 'Expenses', incomes: 'Income', transactionsSubtitle: 'View and edit your expenses and income.', all: 'All', thisWeek: 'This week', thisMonth: 'This month', searchMovements: 'Description, category, or amount', hideUpcomingExpenses: 'Hide upcoming expenses', viewUpcomingExpenses: 'View upcoming expenses', upcomingVisible: 'The Upcoming section is visible', plannedAndRecurring: 'Planned and recurring payments', filters: 'Filters', noExpenses: 'No expenses yet', noResults: 'No results', noExpensesHint: 'Expenses you add will appear here.', noResultsHint: 'Try another search or remove a filter.', clearSearchFilters: 'Clear search and filters', upcoming: 'Upcoming', planned: 'Planned', recurring: 'Recurring', uncategorized: 'Uncategorized', total: 'in total',
    planningSubtitle: 'Your balance, limits, and upcoming transactions.', monthBalance: 'Monthly balance', totalExpenses: 'Total expenses', savings: 'Savings', upcomingMovements: 'Upcoming transactions', upcoming12Months: 'All planned · recurring over 12 months', viewAll: 'View all', noUpcoming: 'You have no upcoming income or expenses.', budgets: 'Budgets', monthLimits: 'Limits for this month', addAction: 'Add', createBudgetHint: 'Create a total or category limit.', totalBudget: 'Total budget', used: 'used', recurringPlural: 'Recurring', recurringForecast: 'Each occurrence appears in the forecast', recurringEmpty: 'Add rent, salary, or subscriptions.', recentEntries: 'Recent income', addIncomeHint: 'Add income to calculate your savings.', weekly: 'Weekly', monthly: 'Monthly', yearly: 'Yearly', next: 'next', tapToEdit: 'tap to edit',
    categoriesSubtitle: 'Customize how you organize your money.', editCategory: 'Edit category', newCategory: 'New category', name: 'Name', description: 'Description', icon: 'Icon', color: 'Color', saveChanges: 'Save changes', saving: 'Saving…', deleteCategory: 'Delete category',
    authSubtitle: 'Understand your money without wasting time logging it.', email: 'Email', password: 'Password', signIn: 'Sign in', or: 'or', createAccount: 'Create an account', incompleteData: 'Missing information', enterCredentials: 'Enter your email and password.', shortPassword: 'Password is too short', sixCharacters: 'Use at least 6 characters.', checkEmail: 'Check your email', confirmEmail: 'We sent you an email to confirm your account.',
    editExpense: 'Edit expense', editIncome: 'Edit income', editSubtitle: 'Update any details you need.', optionalDescription: 'Optional description', chooseCategoryAction: 'Choose category', changeCategory: 'Change category', deleteExpense: 'Delete expense', deleteIncome: 'Delete income', deleteConfirm: 'This action cannot be undone.', delete: 'Delete', updatedExpense: 'Expense updated', updatedIncome: 'Income updated',
    chooseCurrency: 'Choose currency', commonCurrency: 'Choose a commonly used currency.', spent: 'spent',
    close: 'Close', filterExpenses: 'Filter expenses', combineCriteria: 'Combine any criteria you need.', status: 'Status', completed: 'Completed', origin: 'Source', manualSource: 'Manual', textSource: 'Text', voiceSource: 'Voice', minAmount: 'Minimum', maxAmount: 'Maximum', sortBy: 'Sort by', newest: 'Newest', oldest: 'Oldest', highest: 'Highest amount', lowest: 'Lowest amount', clearFilters: 'Clear filters', applyFilters: 'Apply filters', tapToChange: 'Tap to change', noLimit: 'No limit', viewResults: 'View results', filterByCategory: 'Filter by category',
    setupMissing: 'Setup is incomplete', setupPlanning: 'Finish setting up Planning to enable income, budgets, and recurring transactions.', newBudget: 'New budget', editBudget: 'Edit budget', scope: 'Scope', limit: 'Limit', budgetMonth: 'Budget month', allMonthlySpend: 'All monthly spending', saveBudget: 'Save budget', budgetEditorHint: 'Monthly limit for', invalidLimit: 'Enter a valid limit.', budgetSaved: 'Budget saved', budgetUpdated: 'Budget updated', budgetSaveError: 'The budget could not be saved. Check that another one does not exist for the same scope and month.', deleteBudget: 'Delete budget', budgetDeleteConfirm: 'Do you want to delete this monthly limit?', budgetDeleted: 'Budget deleted', budgetDeleteError: 'The budget could not be deleted.', editRecurring: 'Edit recurring transaction', newRecurring: 'New recurring transaction', frequency: 'Frequency', nextDue: 'Next due date', createRecurring: 'Create recurrence', deleteRecurring: 'Delete recurrence', recurringPlaceholder: 'Rent, salary, subscription…',
    privacy: 'Privacy', privacyDescription: 'Descriptions are processed on your device.', connection: 'Connection', connected: 'Service connected', offlineRetry: 'Offline · tap to retry', checkingConnection: 'Checking connection…', version: 'Version', offline: 'Offline', checkInternet: 'Check your connection and tap to retry.',
    intelligentEngine: 'Smart engine', engineReady: 'Loaded and ready to categorize', engineFallback: 'Unavailable · basic categorization is active', engineInstalled: 'Available in the installed application', engineDownloading: 'Downloading to the device', engineStarting: 'Download complete · starting…', engineChecking: 'Checking the local engine…',
    expenseDeleted: 'Expense deleted', incomeDeleted: 'Income deleted',
    categorizationStartError: 'Smart categorization could not start', basicCategorizationActive: 'Basic categorization remains active. Tap to retry.', downloadingLocal: 'Downloading local resources', preparingLocal: 'Preparing categorization', keepUsingApp: 'You can keep using the application.', latestRate: 'Getting the latest rate…', cachedRate: 'Offline · the last available rate is kept', rateReference: 'Daily Frankfurter reference · tap to refresh',
    signOutError: 'Could not sign out.', rateUpdated: 'Exchange rate updated', rateUpdateError: 'Could not update the exchange rate', recurrenceSkipped: 'Transaction skipped. The next occurrence remains scheduled.',
    customPeriod: 'Custom period', from: 'From', to: 'To', apply: 'Apply', cancel: 'Cancel',
  },
  fr: {
    summary: 'Résumé', transactions: 'Mouvements', add: 'Ajouter', planning: 'Planification', categories: 'Catégories',
    day: 'Jour', week: 'Semaine', month: 'Mois', year: 'Année', custom: 'Personnalisé', totalPeriod: 'Total de la période', addExpense: 'Ajouter une dépense',
    settings: 'Réglages', settingsSubtitle: 'Votre compte et vos préférences ExpenseTracker.', account: 'Compte', signedIn: 'Session ouverte',
    currencies: 'Devises', inputCurrency: 'Devise de saisie', displayedCurrency: 'Devise affichée', exchangeRate: 'Taux de change', appearance: 'Apparence', light: 'Clair', dark: 'Sombre',
    language: 'Langue', languageSubtitle: "Langue de l’application", systemLanguage: 'Système',
    plannedMovements: 'Mouvements prévus', automatic: 'Automatique', manual: 'Manuel', automaticDescription: "Ils sont marqués comme réalisés à l’ouverture de l’application le jour prévu.", manualDescription: "Ils restent en attente jusqu’à votre confirmation.",
    categorization: 'Catégorisation', information: 'Informations', signOut: 'Se déconnecter', signingOut: 'Déconnexion…', back: 'Retour',
    chooseCategory: 'Choisir une catégorie', searchCategory: 'Rechercher une catégorie...', searchOrChoose: 'Recherchez ou choisissez une catégorie.', noCategories: 'Aucune catégorie trouvée.', allCategories: 'Toutes les catégories', noCategoryFilter: 'Ne pas filtrer les résultats par catégorie.',
    concept: 'Libellé', amount: 'Montant', date: 'Date', category: 'Catégorie', today: "Aujourd’hui", yesterday: 'Hier', anotherDay: 'Autre jour', plannedExpense: 'Dépense prévue', saveExpense: 'Enregistrer la dépense',
    expense: 'Dépense', income: 'Revenu', newExpense: 'Nouvelle dépense', addFewSteps: 'Ajoutez-la en quelques étapes.', conceptPlaceholder: 'Café, courses…', plannedPending: "Elle restera en attente jusqu’à cette date.", searching: 'Recherche…', selected: 'Sélectionnée', change: 'Modifier', suggested: 'Suggérées', viewAllCategories: 'Voir toutes les catégories', savePlannedExpense: 'Enregistrer la dépense prévue', expenseCurrency: 'Devise de la dépense', invalidAmount: 'Saisissez un montant valide.', selectCategory: 'Choisissez une catégorie.', expenseSaved: 'Dépense ajoutée', plannedExpenseSaved: 'Dépense prévue enregistrée', expenseSaveError: "La dépense n’a pas pu être enregistrée.",
    markCompleted: 'Marquer comme réalisé', movementCompleted: 'Mouvement réalisé', movementCompleteError: "Le mouvement n’a pas pu être finalisé.",
    newIncome: 'Nouveau revenu', incomeSubtitle: 'Enregistrez un salaire, un remboursement ou une autre entrée.', incomePlaceholder: 'Salaire, remboursement…', incomeInfo: 'Ce revenu sera comptabilisé dans le solde et l’épargne du mois.', saveIncome: 'Enregistrer le revenu', incomeCurrency: 'Devise du revenu', incomeSaved: 'Revenu ajouté', incomeSaveError: "Le revenu n’a pas pu être enregistré.",
    expenses: 'Dépenses', incomes: 'Revenus', transactionsSubtitle: 'Consultez et modifiez vos dépenses et revenus.', all: 'Tous', thisWeek: 'Cette semaine', thisMonth: 'Ce mois-ci', searchMovements: 'Description, catégorie ou montant', hideUpcomingExpenses: 'Masquer les dépenses à venir', viewUpcomingExpenses: 'Voir les dépenses à venir', upcomingVisible: 'La section À venir est visible', plannedAndRecurring: 'Paiements prévus et récurrents', filters: 'Filtres', noExpenses: 'Aucune dépense', noResults: 'Aucun résultat', noExpensesHint: 'Les dépenses ajoutées apparaîtront ici.', noResultsHint: 'Essayez une autre recherche ou retirez un filtre.', clearSearchFilters: 'Effacer la recherche et les filtres', upcoming: 'À venir', planned: 'Prévu', recurring: 'Récurrent', uncategorized: 'Sans catégorie', total: 'au total',
    planningSubtitle: 'Votre solde, vos limites et vos mouvements à venir.', monthBalance: 'Solde du mois', totalExpenses: 'Dépenses totales', savings: 'Épargne', upcomingMovements: 'Mouvements à venir', upcoming12Months: 'Tous les prévus · récurrents sur 12 mois', viewAll: 'Tout voir', noUpcoming: 'Vous n’avez aucun revenu ni dépense à venir.', budgets: 'Budgets', monthLimits: 'Limites pour ce mois', addAction: 'Ajouter', createBudgetHint: 'Créez une limite totale ou par catégorie.', totalBudget: 'Budget total', used: 'utilisé', recurringPlural: 'Récurrents', recurringForecast: 'Chaque occurrence apparaît dans la prévision', recurringEmpty: 'Ajoutez loyer, salaire ou abonnements.', recentEntries: 'Revenus récents', addIncomeHint: 'Ajoutez un revenu pour calculer votre épargne.', weekly: 'Hebdomadaire', monthly: 'Mensuel', yearly: 'Annuel', next: 'prochain', tapToEdit: 'toucher pour modifier',
    categoriesSubtitle: 'Personnalisez la façon dont vous organisez votre argent.', editCategory: 'Modifier la catégorie', newCategory: 'Nouvelle catégorie', name: 'Nom', description: 'Description', icon: 'Icône', color: 'Couleur', saveChanges: 'Enregistrer', saving: 'Enregistrement…', deleteCategory: 'Supprimer la catégorie',
    authSubtitle: 'Comprenez votre argent sans perdre de temps à le saisir.', email: 'E-mail', password: 'Mot de passe', signIn: 'Se connecter', or: 'ou', createAccount: 'Créer un compte', incompleteData: 'Informations manquantes', enterCredentials: 'Saisissez votre e-mail et votre mot de passe.', shortPassword: 'Mot de passe trop court', sixCharacters: 'Utilisez au moins 6 caractères.', checkEmail: 'Consultez votre e-mail', confirmEmail: 'Nous vous avons envoyé un e-mail pour confirmer votre compte.',
    editExpense: 'Modifier la dépense', editIncome: 'Modifier le revenu', editSubtitle: 'Modifiez les informations nécessaires.', optionalDescription: 'Description facultative', chooseCategoryAction: 'Choisir une catégorie', changeCategory: 'Changer de catégorie', deleteExpense: 'Supprimer la dépense', deleteIncome: 'Supprimer le revenu', deleteConfirm: 'Cette action est irréversible.', delete: 'Supprimer', updatedExpense: 'Dépense mise à jour', updatedIncome: 'Revenu mis à jour',
    chooseCurrency: 'Choisir une devise', commonCurrency: 'Choisissez une devise courante.', spent: 'dépensé',
    close: 'Fermer', filterExpenses: 'Filtrer les dépenses', combineCriteria: 'Combinez les critères nécessaires.', status: 'Statut', completed: 'Réalisés', origin: 'Origine', manualSource: 'Manuel', textSource: 'Texte', voiceSource: 'Voix', minAmount: 'Minimum', maxAmount: 'Maximum', sortBy: 'Trier par', newest: 'Plus récent', oldest: 'Plus ancien', highest: 'Montant le plus élevé', lowest: 'Montant le plus faible', clearFilters: 'Effacer les filtres', applyFilters: 'Appliquer les filtres', tapToChange: 'Touchez pour modifier', noLimit: 'Sans limite', viewResults: 'Voir les résultats', filterByCategory: 'Filtrer par catégorie',
    setupMissing: 'Configuration incomplète', setupPlanning: 'Terminez la configuration de la planification pour activer revenus, budgets et récurrences.', newBudget: 'Nouveau budget', editBudget: 'Modifier le budget', scope: 'Périmètre', limit: 'Limite', budgetMonth: 'Mois du budget', allMonthlySpend: 'Toutes les dépenses du mois', saveBudget: 'Enregistrer le budget', budgetEditorHint: 'Limite mensuelle pour', invalidLimit: 'Saisissez une limite valide.', budgetSaved: 'Budget enregistré', budgetUpdated: 'Budget mis à jour', budgetSaveError: 'Le budget n’a pas pu être enregistré. Vérifiez qu’il n’en existe pas déjà un pour le même périmètre et le même mois.', deleteBudget: 'Supprimer le budget', budgetDeleteConfirm: 'Voulez-vous supprimer cette limite mensuelle ?', budgetDeleted: 'Budget supprimé', budgetDeleteError: 'Le budget n’a pas pu être supprimé.', editRecurring: 'Modifier la récurrence', newRecurring: 'Nouvelle récurrence', frequency: 'Fréquence', nextDue: 'Prochaine échéance', createRecurring: 'Créer la récurrence', deleteRecurring: 'Supprimer la récurrence', recurringPlaceholder: 'Loyer, salaire, abonnement…',
    privacy: 'Confidentialité', privacyDescription: 'Les libellés sont traités sur votre appareil.', connection: 'Connexion', connected: 'Service connecté', offlineRetry: 'Hors ligne · toucher pour réessayer', checkingConnection: 'Vérification de la connexion…', version: 'Version', offline: 'Hors ligne', checkInternet: 'Vérifiez votre connexion et touchez pour réessayer.',
    intelligentEngine: 'Moteur intelligent', engineReady: 'Chargé et prêt à catégoriser', engineFallback: 'Indisponible · catégorisation de base active', engineInstalled: "Disponible dans l’application installée", engineDownloading: 'Téléchargement sur l’appareil', engineStarting: 'Téléchargement terminé · démarrage…', engineChecking: 'Vérification du moteur local…',
    expenseDeleted: 'Dépense supprimée', incomeDeleted: 'Revenu supprimé',
    categorizationStartError: 'La catégorisation intelligente n’a pas pu démarrer', basicCategorizationActive: 'La catégorisation de base reste active. Touchez pour réessayer.', downloadingLocal: 'Téléchargement des ressources locales', preparingLocal: 'Préparation de la catégorisation', keepUsingApp: 'Vous pouvez continuer à utiliser l’application.', latestRate: 'Récupération du dernier taux…', cachedRate: 'Hors ligne · le dernier taux disponible est conservé', rateReference: 'Référence quotidienne Frankfurter · toucher pour actualiser',
    signOutError: 'Impossible de se déconnecter.', rateUpdated: 'Taux de change actualisé', rateUpdateError: 'Impossible d’actualiser le taux', recurrenceSkipped: 'Mouvement ignoré. La prochaine occurrence reste programmée.',
    customPeriod: 'Période personnalisée', from: 'Du', to: 'Au', apply: 'Appliquer', cancel: 'Annuler',
  },
} as const;

export type TranslationKey = keyof typeof messages.es;

export function translate(language: AppLanguage, key: TranslationKey) {
  return messages[language][key] ?? messages.en[key];
}
